version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: printerpstgrs-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backups:/backups
      - ./custom-init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres-data:
    driver: local
